# Define the priors in computational space
# there are many other examples in test/TOMLInterface/uq_test_parameters.toml

[initial_thickness]
prior = "VectorOfParameterized(repeat([Normal(500,50)],4))"
constraint = "repeat([no_constraint()],4)"
description = """
The prior for the initial thickness samples of the simulation is a Normal distribution with specified (mean,sd) 
"""
